name: Create Release on Version Update

on:
  push:
    branches:
      - main
    paths:
      - 'pyproject.toml'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install toml package
        run: |
          python -m pip install toml

      - name: Get pyproject.toml version
        id: get_version
        run: |
          python -c "import toml; print(f'version={toml.load(\"pyproject.toml\")[\"project\"][\"version\"]}')" >> $GITHUB_OUTPUT

      - name: Check if release for this version already exists
        id: check_release
        run: |
          set +e
          curl -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.get_version.outputs.version }}" \
          > release.json
          
          if grep -q "Not Found" release.json; then
            echo "::set-output name=release_exists::false"
          else
            echo "::set-output name=release_exists::true"
          fi

      - name: Create GitHub Release
        if: steps.check_release.outputs.release_exists == 'false'
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: New release triggered by version update in pyproject.toml